### ISSUE TITLE
Dark display

### ISSUE THREAD

**Issue by Doisaac** [marombeltran/marombeltran.github.io#1]
Hey how are you? I think you are still working on it, but if you haven't noticed it yet. When a user is in "dark mode". Font disappears.

![Font-color](https://user-images.githubusercontent.com/53149834/203464624-92475da0-70d3-4ddb-b7f2-a8fcd47253ce.png)

😅Also I forgot to mention I come from your "UES group message".

**Comment by marombeltran** [comment]
Hi @Doisaac, thanks for notifying, I have made the change, it helped me because I had not reviewed it in dark mode.
